### ISSUE TITLE
Empty Definitions

### ISSUE THREAD

**Issue by philmb3487** [geajack/Wordology#1]
First of all, amazing project! This is the best way to learn vocabulary, in my opinion, with a lot of reading.

For this issue:  in my language I know a lot of words, but entering a definition for all of them is quite tedious. is there a possibility to green words that you know without having to enter all the definitions? if you don't, it stays red. in a way, this is good behaviour because this allows you to move a word back to "don't know".

**Comment by jack-jjm** [comment]
I see, so you'd like a way to make a word go green (or at least not be red) without having to type in a definition? Like a sort of "Ignore this word" feature?

Currently there's no way to do this, since as you've found out, if you just type in no definition and click OK, the word stays red. I don't really plan on changing that since I think it helps prevent accidentally "greening" a word without typing a definition. The real trouble is that I can't think of a good place to put a "ignore this word" option in the interface. Since clicking opens the popup window, you would still have to open that up and press "ignore word" or something, which seems like it would still be kind of tedious.

Personally, when I use Wordology with my target language (where I also know quite a lot of words already), I don't necessarily add every single word. I mostly just add the words I don't know, or even just the ones that I need in order to understand the page I'm reading. I add the words I know a little bit at a time, now and again. It helps make it less tedious.

When you have an intermediate level in a language, there's definitely an initial hump of adding a lot of words you know, but it evens out after a while. And if it doesn't even out... maybe you don't really need Wordology to be reading that language.

Also, note that you can import word lists into Wordology in the options page. If enough of a community develops around the add-on, people could share their word lists, which could also help in situations like this. In fact, since you clearly know programming, you could even make such a word list yourself - the JSON format is very simple and detailed in the Help page (in the addon Options page).

Not convinced we need an "ignore word" or "empty definition" feature as you call it, but I'll keep it in mind.

**Comment by philmb3487** [comment]
Haha. You're totally right on many levels, I probably don't need the add on to read in German. The easy way I can see is to have another button that just says "i know this" and inserts the word with the same id.

Cheers.

**Comment by heberleh** [comment]
I had similar idea of this. I just checked if it would be good for me, but the redish page does not help me localize words that I don't know to practice them or pay more attention. 
Maybe it is a different purpose, but there is a website (https://bliubliu.com/en/) that the learning process was based on marking words as red when you don't know it. First, an AI marked in red according to a test made initially, then, it showed videos with transcript where you would mark as red or as green. Green words stop to appear as green to not pollute the text with colours, so that you focus more on still-learning-words and unknown-words.
So, in case this project goes to other direction in a future... here are some ideas, not needing AI:
- I have my on texts here, so I could enter them as input and so these words would not appear as red (nor as green), would be just ignored, stay as in the original text;
- Add to the 'known words'  all words of a selection;
- For words that are not in my vocabulary: mark as red;
- For words I translated and I am learning, mark as yellow; Maybe even include levels of difficulty for further ranking of words to practice by writing/speaking;
- If I see a red word or yellow that I feel confident, I click to mark as green (next texts this word will not have a color at all).
I would like to participate of such a project, despite right now I am a bit busy trying to finish my phd and find a job. With the vocabulary builder, visualization tools could help too.
Congratulations for the initiative! I saw your app been mentioned in the Canguro English video: https://www.youtube.com/watch?v=XbjGZHeLUn8
